My_Blog_Project/App_blog/urls.py
from django.urls import path
from App_blog import views

app_name = 'App_blog'

urlpatterns = [
    path('', views.Blog_List_View.as_view(), name="blog_list"),
    path('write_blog/', views.Write_Blog_View.as_view(), name="write_blog"),
    path('blog_details/<slug:slug>/', views.Blog_Details_View, name="blog_details"),
    path('like_blog/<pk>/', views.Like_View, name="like_blog"),
    path('unlike_blog/<pk>/', views.Unlike_View, name="unlike_blog"),
    path('my_blogs/', views.MyBlogs_View.as_view(), name="my_blogs"),
    path('edit_blog/<pk>/', views.Update_Blog_View.as_view(), name="edit_blog"),
]

My_Blog_Project/My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_login.urls')),
    path('blog/', include('App_blog.urls')),
    path('', views.index, name="index"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Blog_Project/App_blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Put a title...")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name="What's on your mind...?")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name='Image')
    publish_date = models.DateTimeField(auto_now_add=True)
    last_update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-publish_date',)

    def __str__(self):
        return self.blog_title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comment_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_user')
    comment = models.TextField(verbose_name='Wanna tell something...?')
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-comment_date',)

    def __str__(self):
        return self.comment


class Like(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='like_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='like_user')


    def __str__(self):
        return str(self.user) + "   likes   " + str(self.blog.blog_title)

My_Blog_Project/App_blog/forms.py
from django import forms
from App_blog.models import Blog, Comment

class Comment_Form(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

My_Blog_Project/App_blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView, TemplateView, View
from App_blog.models import Blog, Comment, Like
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
import uuid
from . import forms

# Create your views here.

class Blog_List_View(ListView):
    model = Blog
    context_object_name = 'blogs'
    template_name = 'App_blog/blog_list.html'
    # queryset = Blog.objects.order_by('-publish_date')

class Write_Blog_View(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'App_blog/create_blog.html'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        title = obj.blog_title
        obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        obj.save()
        return HttpResponseRedirect(reverse('index'))

@login_required
def Blog_Details_View(request, slug):
    blog = Blog.objects.get(slug=slug)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    if already_liked:
        liked = True
    else:
        liked = False

    comment_form = forms.Comment_Form()
    if request.method == 'POST':
        comment_form = forms.Comment_Form(request.POST)
        if comment_form.is_valid():
            comment_obj = comment_form.save(commit=False)
            comment_obj.user = request.user
            comment_obj.blog = blog
            comment_obj.save()
            return HttpResponseRedirect(reverse('App_blog:blog_details', kwargs={'slug':slug}))

    return render(request, 'App_blog/blog_details.html', context={'blog' : blog, 'comment_form' : comment_form, 'liked':liked })


@login_required
def Like_View(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    if not already_liked:
        new_obj = Like(blog=blog, user=user)
        new_obj.save()
    return HttpResponseRedirect(reverse('App_blog:blog_details', kwargs={'slug' : blog.slug}))


@login_required
def Unlike_View(request, pk):
        blog = Blog.objects.get(pk=pk)
        user = request.user
        already_liked = Like.objects.filter(blog=blog, user=user)
        already_liked.delete()
        return HttpResponseRedirect(reverse('App_blog:blog_details', kwargs={'slug' : blog.slug}))


class MyBlogs_View(LoginRequiredMixin, TemplateView):
    model = Blog
    template_name = 'App_blog/my_blogs.html'


class Update_Blog_View(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'App_blog/edit_blog.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('App_blog:blog_details', kwargs={'slug' : self.object.slug})

My_Blog_Project/templates/App_blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}

{% block body_block %}
  <div class="row" style="padding-top:20px">
    <div class="col-sm-6">
      <h3>{{blog.blog_title}}</h3>
      <h5>Posted By : <a href="#">@{{blog.author}}</a></h5>
      <i><h6>Published On : {{blog.publish_date}}</h6></i>
      <i><h6>Updated On : {{blog.last_update_date}}</h6></i>
      <i><h6>{{blog.like_blog.count}} Likes | {{blog.comment_blog.count}} Comments</h6></i>
    </div>

    <div class="col-sm-6">
      <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
    </div>

    <p>{{blog.blog_content|linebreaks}}</p>
  </div>


  <hr style="border:1px solid red">

  {% if not liked %}
    <a href="{% url 'App_blog:like_blog' pk=blog.pk %}"><i class="fa fa-thumbs-up fa-3x" aria-hidden="true"></i></a>
  {% else %}
    <a href="{% url 'App_blog:unlike_blog' pk=blog.pk %}"><i class="fa fa-thumbs-down fa-3x" aria-hidden="true"></i></a>
  {% endif %}


  <div class="row">
    <div class="col-sm-2">

    </div>
    <div class="col-sm-6">
      <form method="POST">
        {{comment_form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-info btn-sm">Comment</button>
      </form>
      <br>
      <h4>Comments :</h4><br>
      {% for comment in blog.comment_blog.all %}
        <h6><a href="#">@{{comment.user}}</a> : {{comment.comment}}</h6>
        <p>{{comment.comment_date}}</p>

        <hr style="border:1px solid green">

      {% endfor %}
    </div>

    <div class="col-sm-4">

    </div>

  </div>
{% endblock %}

My_Blog_Project/templates/App_blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filter %}

{% block title_block %} Home {% endblock %}

{% block body_block %}
  {% for blog in blogs %}
    <h3>{{blog.blog_title}}</h3>
    <h6>{{blog.publish_date}}</h6>
    <div class="row">

      <div class="col-sm-4">
        <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
      </div>

      <div class="col-sm-8">
        <p>{{blog.blog_content|linebreaks|range_blog}} <a href="{% url 'App_blog:blog_details' slug=blog.slug %}">Read More</a></p>
        <h6>Posted By <a href="#">@{{blog.author}}</a></h6>
        <i><h6>{{blog.like_blog.count}} Likes | {{blog.comment_blog.count}} Comments</h6></i>
      </div>

    </div>
    <hr style="border:2px solid green">
  {% endfor %}

{% endblock %}

My_Blog_Project/templates/App_blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Blog {% endblock %}

{% block body_block %}
  <h3>Explore Your Mind...</h3>
  <form method="POST" enctype="multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit"class="btn btn-success btn-sm">Post</button>
  </form>
{% endblock %}

My_Blog_Project/templates/App_blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Edit Blog {% endblock %}

{% block body_block %}
{% if blog.author == user %}
  <form enctype="multipart/form-data" method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit"class="btn btn-success btn-xs">Update</button>
  </form>
{% else %}
<div class="alert alert-danger">
  You Are Not Allowed To See This. Error 404.
</div>
{% endif %}
{% endblock %}

My_Blog_Project/templates/App_blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filter %}
{% block title_block %} {{user}} Blogs {% endblock %}

{% block body_block %}
  {% for blog in user.post_author.all %}
    <div class="row" style="padding-top:20px">
      <div class="col-sm-6">
        <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" width=100%>
      </div>
      <div class="col-sm-6">
        <h4>{{blog.blog_title}}</h4>
        <i><h6> {{blog.publish_date}} | {{blog.like_blog.count}} Likes | {{blog.comment_blog.count}} Comments
         |  <a href="{% url 'App_blog:edit_blog' pk=blog.pk %}" class="btn btn-info btn-sm">Edit</a></h6></i>
        <br>
        <p>{{blog.blog_content | range_blog | linebreaks}}</p>
        <i><a href="{% url 'App_blog:blog_details' slug=blog.slug %}">Read More</a></i>
      </div>

    </div>
    <hr style="border:1px solid green">
  {% endfor %}
{% endblock %}