My_Blog_Project/App_blog/urls.py
from django.urls import path
from App_blog import views

app_name = 'App_blog'

urlpatterns = [
    path('', views.Blog_List_View.as_view(), name="blog_list"),
    path('write_blog/', views.Write_Blog_View.as_view(), name="write_blog"),
    path('blog_details/<slug:slug>/', views.Blog_Details_View, name="blog_details"),
    path('like_blog/<pk>/', views.Like_View, name="like_blog"),
    path('unlike_blog/<pk>/', views.Unlike_View, name="unlike_blog"),
    path('my_blogs/', views.MyBlogs_View.as_view(), name="my_blogs"),
    path('edit_blog/<pk>/', views.Update_Blog_View.as_view(), name="edit_blog"),
]

My_Blog_Project/App_login/urls.py
from django.urls import path
from App_login import views

app_name = 'App_login'

urlpatterns = [
    path('sign_up/', views.SignUp, name="sign_up"),
    path('login/', views.UserLogin, name="login"),
    path('logout/', views.UserLogout, name="logout"),
    path('user_profile/', views.UserProfile, name="user_profile"),
    path('change_profile/', views.UserChangeProfile, name="change_profile"),
    path('password/', views.ChangePassword, name="password"),

    path('add-pro-pic/', views.Add_Profile_Pic, name="add_pro_pic"),
    path('change_pro_pic/', views.Change_Profile_Pic, name="change_pro_pic"),
]

My_Blog_Project/My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_login.urls')),
    path('blog/', include('App_blog.urls')),
    path('', views.index, name="index"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Blog_Project/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
    <title>{% block title_block %} Blogs {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}"><img src="/media/home_logo.png" width="50px"></a>
      </li>
      {% if user.is_authenticated %}
        <div class=" nav-item active dropdown">
          <a class="nav-link dropdown-toggle" id="navbardrop" data-toggle="dropdown">{{user.username}}</a>

          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'App_blog:write_blog' %}">Write Blog</a>
            <a class="dropdown-item" href="{% url 'App_blog:my_blogs' %}">My Blogs</a>
            <a class="dropdown-item" href="{% url 'App_login:user_profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'App_login:logout' %}">Logout</a>
          </div>

        </div>
      {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'App_login:sign_up' %}">Sign Up</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'App_login:login' %}">Login</a>
        </li>
      {% endif %}
    </ul>
  </nav>

  <div class="container">
    {% block body_block %}

    {% endblock %}
  </div>

  </body>
</html>