My_Blog_Project/App_blog/urls.py
from django.urls import path
from App_blog import views

app_name = 'App_blog'

urlpatterns = [
    path('', views.Blog_List_View.as_view(), name="blog_list"),
    path('write_blog/', views.Write_Blog_View.as_view(), name="write_blog"),
    path('blog_details/<slug:slug>/', views.Blog_Details_View, name="blog_details"),
    path('like_blog/<pk>/', views.Like_View, name="like_blog"),
    path('unlike_blog/<pk>/', views.Unlike_View, name="unlike_blog"),
    path('my_blogs/', views.MyBlogs_View.as_view(), name="my_blogs"),
    path('edit_blog/<pk>/', views.Update_Blog_View.as_view(), name="edit_blog"),
]

My_Blog_Project/App_login/urls.py
from django.urls import path
from App_login import views

app_name = 'App_login'

urlpatterns = [
    path('sign_up/', views.SignUp, name="sign_up"),
    path('login/', views.UserLogin, name="login"),
    path('logout/', views.UserLogout, name="logout"),
    path('user_profile/', views.UserProfile, name="user_profile"),
    path('change_profile/', views.UserChangeProfile, name="change_profile"),
    path('password/', views.ChangePassword, name="password"),

    path('add-pro-pic/', views.Add_Profile_Pic, name="add_pro_pic"),
    path('change_pro_pic/', views.Change_Profile_Pic, name="change_pro_pic"),
]

My_Blog_Project/My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_login.urls')),
    path('blog/', include('App_blog.urls')),
    path('', views.index, name="index"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Blog_Project/App_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    pro_pic = models.ImageField(upload_to='profile_pics')

    def __str__(self):
        return self.user.username

My_Blog_Project/App_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from App_login.models import UserProfile

class SignUpForms(UserCreationForm):
    email = forms.EmailField( label='Email Address', required=True)
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email')


class ChangeProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = {'username', 'email', 'first_name', 'last_name', 'password'}


class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['pro_pic',]

My_Blog_Project/App_login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from App_login.forms import SignUpForms, ChangeProfileForm, ProfilePic
# Create your views here.

def SignUp(request):
    new_form = SignUpForms()
    registered = False
    if request.method == 'POST':
        new_form = SignUpForms(data = request.POST)
        if new_form.is_valid():
            new_form.save()
            registered = True
    context = {
        'registered' : registered,
        'new_form' : new_form,
    }
    return render(request, 'App_login/sign_up.html', context=context)


def UserLogin(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    return render(request, 'App_login/login.html', context={'form' : form})

@login_required
def UserLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def UserProfile(request):
    return render(request, 'App_login/user_profile.html', context={})


@login_required
def UserChangeProfile(request):
    current_user = request.user
    form = ChangeProfileForm(instance=current_user)
    if request.method == 'POST':
        form = ChangeProfileForm(data=request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            # form = ChangeProfileForm(instance=current_user)
            return UserProfile(request)
    return render(request, 'App_login/change_profile.html', context={'form' : form})

@login_required
def ChangePassword(request):
    changed = False
    current_user = request.user
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
            return UserProfile(request)
    return render(request, 'App_login/change_pass.html', context={'form' : form, 'changed' : changed})


@login_required
def Add_Profile_Pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            return HttpResponseRedirect(reverse('App_login:user_profile'))
    return render(request, 'App_login/add_pro_pic.html', context={'form' : form})


@login_required
def Change_Profile_Pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_login:user_profile'))
    return render(request, 'App_login/add_pro_pic.html', context={'form' : form})

My_Blog_Project/templates/App_login/add_pro_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Profile Picture {% endblock %}

{% block body_block %}
  <h3>Change Profile Picture :</h3>
  <form method="POST" enctype="multipart/form-data">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Add</button>
  </form>
{% endblock %}

My_Blog_Project/templates/App_login/change_pass.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %} Change Profile {% endblock %}

{% block body_block %}
  {% if changed %}
    <div class="alert alert-success">
      Password Changed Successfully....!
    </div>
  {% else %}
    <form method="POST">
      {{form|crispy}}
      {% csrf_token %}
      <button type="submit" name="button" class="btn btn-success btn-sm">Change</button>
    </form>
  {% endif %}
{% endblock %}

My_Blog_Project/templates/App_login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %} Change Profile {% endblock %}

{% block body_block %}
  <form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" name="button" class="btn btn-success btn-sm">Change</button>
  </form>
{% endblock %}

My_Blog_Project/templates/App_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %} Login {% endblock %}

{% block body_block %}
  <h3>Login :</h3>
  <form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" class="btn btn-info btn-sm">Login</button>
  </form>
{% endblock %}

My_Blog_Project/templates/App_login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title_block %} Sign Up {% endblock %}

{% block body_block %}
  {% if registered %}
    <div class="alert alert-info" style="padding-top:20px">
      Account successfully created... <a href="{% url 'App_login:login' %}">Login Here</a>
    </div>

  {% else %}
    <form method="POST" style="padding-top:20px">
      {{ new_form|crispy }}
      {% csrf_token %}
      <button type="submit" class="btn btn-success btn-sm">Sign Up</button>
    </form>
    <br>
    <p>Already have an account ? <a href="{% url 'App_login:login' %}">Login Here</a> </p>

  {% endif %}
{% endblock %}

My_Blog_Project/templates/App_login/user_profile.html
{% extends 'base.html' %}

{% block title_block %} User Profile {% endblock %}

{% block body_block %}
  <h3>User Information</h3>
  {% if user.user_profile %}
    <img src="/media/{{user.user_profile.pro_pic}}" alt="Profile_Picture" class="img-rounded" width="100px">
    <br>
    <a href="{% url 'App_login:change_pro_pic' %}" class="btn btn-info btn-sm">Update Profile Picture</a>
    <br>
    <br>
  {% else %}
    <img src="/media/profile_pics/avatar-male.jpg" alt="Profile Picture Demo" class="img-rounded" width="100px">
    <br>
    <a href="{% url 'App_login:add_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
    <br>
    <br>
  {% endif %}
  <p>Name : {{user.first_name}} {{user.last_name}}</p>
  <p>Username : {{user.username}}</p>
  <p>Email Address : {{user.email}}</p>
  <br>
  <a href="{% url 'App_login:change_profile' %}" class="btn btn-warning btn-sm">Change User Info</a>
{% endblock %}